name: Generate WSL NixOS Image

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install nixpkgs
      run: |
        curl -L https://nixos.org/nix/install | sh
        source /home/runner/.nix-profile/etc/profile.d/nix.sh

    - name: Build image itself
      run: ./build.sh ./install.tar.gz

    - name: Upload the artifacts
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'install.tar.gz'
